import { NextResponse, NextRequest } from "next/server";

import getOrCreateDB from "../models/server/dbSetup";
import getOrCreateStorage from "../models/server/storageSetup";


// always runs this middleware before loading

export async function middleware(request: NextRequest) {
  await Promise.all([
    getOrCreateDB(),
    getOrCreateStorage()
  ])
    return NextResponse.next();
}

// matches paths 
export const config = {
    // middleware dosent run at the matched path

    /*Match all the paths except the ones that start with : 
    -api
    - _next/static
    - _next/image
    - favicon.com
    */

  matcher: [
    // generated by gpt-
    "/((?!api|_next/static|_next/image|favicon.ico).*)",
  ]
};
